import {
    aminBG,
    aryanaBG, 
    baharanBG, 
    erfanBG, 
    fatemehBG, 
    fathimaBG, 
    hamidrezaBG, 
    melikaBG, 
    minaBG, 
    mohammadBG, 
    motaharehBG, 
    pegahBG, 
    reihanehBG, 
    unkown,
    saminBG,
    royanBG,
    gezalBG,
    edwinBG,
    zahraBG,
    event2023Pic1,
    event2023Pic2,
    event2023Pic3,
    event2023Pic4,
    event2023Pic5,
    event2023Pic6,
    event2024,
    heroimage,
    alina_talk30,
    alina_talk50,
    alina_talk100,
    andrew_talk20,
    andrew_talk150,
    andrew_talk210,
    flore_talk60,
    flore_talk180,
    flore_talk200,
    janet_talk30,
    janet_talk50,
    janet_talk60,
    kira_talk30,
    kira_talk70,
    kira_talk80,
    leila_talk40,
    leila_talk80,
    leila_talk20,
    myra_talk20,
    myra_talk60,
    myra_talk90,
    peggy_talk50,
    peggy_talk80,
    peggy_talk120,
    galleryImage1,
    sliderImage1
} from "../../assets";

export const slides = [
  {
    id: "1",
    src: sliderImage1,
    title: "TEDxAveLorne 2023",
    description: "TEDxAveLorne 2023",
  },
  {
    id: "2",
    src: event2023Pic1,
    title: "TEDxAveLorne 2023",
    description: "TEDxAveLorne 2023",
  },
  {
    id: "3",
    src: event2023Pic2,
    title: "TEDxAveLorne 2023",
    description: "TEDxAveLorne 2023",
  },
  {
    id: "4",
    src: event2023Pic5,
    title: "TEDxAveLorne 2023",
    description: "TEDxAveLorne 2023",
  },
  {
    id: "5",
    src: event2023Pic4,
    title: "TEDxAveLorne 2023",
    description: "TEDxAveLorne 2023",
  },
  {
    id: "6",
    src: event2023Pic3,
    title: "TEDxAveLorne 2023",
    description: "TEDxAveLorne 2023",
  },
  {
    id: "7",
    src: galleryImage1,
    title: "TEDxAveLorne 2023",
    description: "TEDxAveLorne 2023",
  },
  {
    id: "8",
    src: alina_talk50,
    title: "Alina Gutierrez Mejia",
    description: "Let Me Draw What I Mean",
  },
  {
    id: "9",
    src: andrew_talk20,
    title: "Andrew Churchil",
    description: "TEDxAveLorne 2023",
  },
  {
    id: "10",
    src: flore_talk60,
    title: "Flore Deshayes",
    description: "La pouvoir du silence dans nos interactions humaines",
  },
  {
    id: "11",
    src: janet_talk50,
    title: "Janet Perlman",
    description: "TEDxAveLorne 2023",
  },
  {
    id: "12",
    src: kira_talk30,
    title: "Kira Dolhan",
    description: "Personal strength is not always so personal",
  },
  {
    id: "13",
    src: leila_talk40,
    title: "Leila Kosseim",
    description: "How can we make computers understand natural language?",
  },
  {
    id: "14",
    src: myra_talk60,
    title: "Myra Virgil",
    description: "TEDxAveLorne 2023",
  },
  {
    id: "15",
    src: peggy_talk120,
    title: "Peggy Bell",
    description: "Revolutionizing Mining: From Challenges to Empowerment",
  },
  {
    id: "16",
    src: alina_talk30,
    title: "Alina Gutierrez Mejia",
    description: "Let Me Draw What I Mean",
  },
  {
    id: "17",
    src: andrew_talk210,
    title: "Andrew Churchil",
    description: "TEDxAveLorne 2023",
  },
  {
    id: "18",
    src: flore_talk180,
    title: "Flore Deshayes",
    description: "La pouvoir du silence dans nos interactions humaines",
  },
  {
    id: "19",
    src: janet_talk60,
    title: "Janet Perlman",
    description: "TEDxAveLorne 2023",
  },
  {
    id: "20",
    src: kira_talk70,
    title: "Kira Dolhan",
    description: "Personal strength is not always so personal",
  },
  {
    id: "21",
    src: leila_talk80,
    title: "Leila Kosseim",
    description: "How can we make computers understand natural language?",
  },
  {
    id: "22",
    src: myra_talk20,
    title: "Myra Virgil",
    description: "TEDxAveLorne 2023",
  },
  {
    id: "23",
    src: peggy_talk50,
    title: "Peggy Bell",
    description: "Revolutionizing Mining: From Challenges to Empowerment",
  },
  {
    id: "24",
    src: alina_talk100,
    title: "Alina Gutierrez Mejia",
    description: "Let Me Draw What I Mean",
  },
  {
    id: "25",
    src: andrew_talk150,
    title: "Andrew Churchil",
    description: "TEDxAveLorne 2023",
  },
  {
    id: "26",
    src: flore_talk200,
    title: "Flore Deshayes",
    description: "La pouvoir du silence dans nos interactions humaines",
  },
  {
    id: "27",
    src: janet_talk30,
    title: "Janet Perlman",
    description: "TEDxAveLorne 2023",
  },
  {
    id: "28",
    src: kira_talk80,
    title: "Kira Dolhan",
    description: "Personal strength is not always so personal",
  },
  {
    id: "29",
    src: leila_talk20,
    title: "Leila Kosseim",
    description: "How can we make computers understand natural language?",
  },
  {
    id: "30",
    src: myra_talk90,
    title: "Myra Virgil",
    description: "TEDxAveLorne 2023",
  },
  {
    id: "31",
    src: peggy_talk80,
    title: "Peggy Bell",
    description: "Revolutionizing Mining: From Challenges to Empowerment",
  },
  // {
  //   id: "6",
  //   src: event2023Pic6,
  //   title: "TEDxAveLorne 2023",
  //   description: "TEDxAveLorne 2023",
  // },
  // {
  //   id: "20",
  //   src: heroimage,
  //   title: "TEDxAveLorne 2023",
  //   description: "TEDxAveLorne 2023",
  // },
  {
    id: "40",
    src: saminBG,
    title: "Samin Majidi",
    description: "Samin Majidi",
  },
  {
    id: "50",
    src: fatemehBG,
    title: "Fatemeh Tavanaei",
    description: "Fatemeh Tavanaei",
  },
  {
    id: "60",
    src: erfanBG,
    title: "Mohammaderfan Mohit",
    description: "Mohammaderfan Mohit",
  },
  {
    id: "80",
    src: melikaBG,
    title: "Melika Seyedi",
    description: "Melika Seyedi",
  },
  {
    id: "90",
    src: hamidrezaBG,
    title: "Hamidreza Ermagan",
    description: "Hamidreza Ermagan",
  },
  {
    id: "100",
    src: baharanBG,
    title: "Baharan Nouriinanloo",
    description: "Baharan Nouriinanloo",
  },
  {
    id: "110",
    src: motaharehBG,
    title: "Motahareh Pourrahimi",
    description: "Motahareh Pourrahimi",
  },
  {
    id: "120",
    src: royanBG,
    title: "Royan Jafari",
    description: "Royan Jafari",
  },
  {
    id: "130",
    src: fathimaBG,
    title: "Fathima Nihatha Lathiff",
    description: "Fathima Nihatha Lathiff",
  },
  {
    id: "140",
    src: minaBG,
    title: "Mina Taraghi",
    description: "Mina Taraghi",
  },
  {
    id: "150",
    src: mohammadBG,
    title: "Mohammad Zaid",
    description: "Mohammad Zaid",
  },
  {
    id: "160",
    src: aryanaBG,
    title: "Aryana Haghjoo",
    description: "Aryana Haghjoo",
  },
  {
    id: "170",
    src: pegahBG,
    title: "Pegah Einakchi",
    description: "Pegah Einakchi",
  },
  {
    id: "180",
    src: edwinBG,
    title: "Edwin Meriaux",
    description: "Edwin Meriaux",
  },
  {
    id: "190",
    src: gezalBG,
    title: "Gezal Najafi",
    description: "Gezal Najafi",
  },
  {
    id: "200",
    src: zahraBG,
    title: "Zahra Ahmadi",
    description: "Zahra Ahmadi",
  },
  {
    id: "210",
    src: aminBG,
    title: "Mohammad Amin Shamshiri",
    description: "Mohammad Amin Shamshiri",
  },
];
